# Generated by Django 5.1.3 on 2024-11-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
